apiVersion: v1
kind: Service
metadata:
  labels:
    app: resume
  name: resume
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: resume
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: resume
  labels:
    app: resume
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resume
  template:
    metadata:
      labels:
        app: resume
    spec:
      containers:
        - image: 'gcr.io/compliance-167400/resume'
          name: resume
          ports:
            - containerPort: 80
              name: resume
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
